SELECT * FROM AUTHOR
SELECT * FROM BOOK
SELECT * FROM PUBLISHER
-- Part – A:
-- 1. List all books with their authors.
SELECT TITLE,AUTHORNAME FROM BOOK B 
INNER JOIN AUTHOR A ON B.AUTHORID = A.AUTHORID
-- 2. List all books with their publishers.
SELECT TITLE,PUBLISHERNAME FROM BOOK B INNER JOIN PUBLISHER P ON B.PUBLISHERID=P.PUBLISHERID
-- 3.List all books with their authors and publishers.
SELECT TITLE,PUBLISHERNAME,AUTHORNAME FROM BOOK B
INNER JOIN AUTHOR A ON B.AUTHORID=A.AUTHORID
JOIN PUBLISHER P ON B.PUBLISHERID=P.PUBLISHERID
-- 4.List all books published after 2010 with their authors and publisher and price.
SELECT TITLE,PUBLISHERNAME,AUTHORNAME,PRICE,PUBLICATIONYEAR FROM BOOK B
INNER JOIN AUTHOR A ON B.AUTHORID=A.AUTHORID
JOIN PUBLISHER P ON B.PUBLISHERID=P.PUBLISHERID
WHERE PUBLICATIONYEAR>2010
-- 5.List all authors and the number of books they have written.
SELECT COUNT(BOOKID),AUTHORNAME FROM BOOK B
INNER JOIN AUTHOR A 
ON B.AUTHORID=A.AUTHORID
GROUP BY AUTHORNAME
-- 6.List all publishers and the total price of books they have published.
SELECT SUM(PRICE),PUBLISHERNAME FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME
-- 7.List authors who have not written any books.
SELECT TITLE,AUTHORNAME FROM BOOK B 
RIGHT JOIN AUTHOR A ON B.AUTHORID = A.AUTHORID
WHERE BOOKID IS NULL
-- 8.Display the total number of books written by each author along with the average price of their books.
SELECT COUNT(BOOKID),AVG(PRICE),AUTHORNAME FROM BOOK B 
INNER JOIN AUTHOR A ON B.AUTHORID = A.AUTHORID
GROUP BY AUTHORNAME
-- 9.lists each publisher along with the total number of books they have published, sorted from highest to
-- lowest.
SELECT COUNT(P.PUBLISHERID) AS BOOKS_PUBLISHED,PUBLISHERNAME FROM BOOK B 
INNER JOIN PUBLISHER P 
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME
ORDER BY COUNT(P.PUBLISHERID) DESC

-- 10. Display number of books published each year.
SELECT PUBLICATIONYEAR,COUNT(P.PUBLISHERID) AS NO_OF_BOOKS_PUBLISHED FROM BOOK B
INNER JOIN PUBLISHER P
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLICATIONYEAR

-- 11. List the publishers whose total book prices exceed 500, ordered by the total price.
SELECT SUM(PRICE),PUBLISHERNAME FROM BOOK B  
INNER JOIN PUBLISHER P  
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME
HAVING SUM(PRICE)>500
-- 12. List most expensive book for each author, sort it with the highest price.
SELECT AUTHORNAME,MAX(PRICE) FROM BOOK B 
INNER JOIN AUTHOR A
ON B.AUTHORID=A.AUTHORID 
GROUP BY AUTHORNAME
ORDER BY MAX(PRICE) DESC

-- 13. Display publisher name and difference between maximum and minimum book price.
SELECT MAX(PRICE)-MIN(PRICE),PUBLISHERNAME FROM BOOK B  
INNER JOIN PUBLISHER P  
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME
-- 14. List publisher name and total price of books published each year.
SELECT PUBLISHERNAME,SUM(PRICE),PUBLICATIONYEAR FROM BOOK B  
INNER JOIN PUBLISHER P 
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME,PUBLICATIONYEAR
-- 15. Display author name and total price of books sorted by highest total price.
SELECT AUTHORNAME,SUM(PRICE) FROM BOOK B 
INNER JOIN AUTHOR A   
ON B.AUTHORID=A.AUTHORID
GROUP BY AUTHORNAME
ORDER BY SUM(PRICE) DESC

CREATE TABLE EMPLOYEE_MASTER (
    EmployeeNo VARCHAR(3) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    ManagerNo VARCHAR(3),
    FOREIGN KEY (ManagerNo) REFERENCES EMPLOYEE_MASTER(EmployeeNo)
);

INSERT INTO EMPLOYEE_MASTER (EmployeeNo, Name, ManagerNo)
VALUES
('E01', 'Tarun', NULL),
('E02', 'Rohan', 'E02'),
('E03', 'Priya', 'E01'),
('E04', 'Milan', 'E03'),
('E05', 'Jay', 'E01'),
('E06', 'Anjana', 'E04');

-- 16. Retrieve the names of employee along with their manager’s name from the Employee table.
SELECT E1.NAME,E2.NAME 
FROM EMPLOYEE_MASTER E1 
JOIN EMPLOYEE_MASTER E2
ON E1.MANAGERNO=E2.EMPLOYEENO
-- 17. Display employees who are managers.
SELECT DISTINCT E2.NAME
FROM EMPLOYEE_MASTER E1
JOIN EMPLOYEE_MASTER E2
ON E1.ManagerNo=E2.EmployeeNo

-- 18. Display number of employees working under each manager.
SELECT E2.NAME, COUNT(E1.EMPLOYEENO) 
FROM EMPLOYEE_MASTER E1
JOIN EMPLOYEE_MASTER E2 
ON E1.ManagerNo=E2.EmployeeNo
GROUP BY E2.NAME
-- 19. Display the employee’s name along with their manager’s name and senior manager name.
SELECT E1.NAME,E2.NAME,E3.NAME 
FROM EMPLOYEE_MASTER E1 
LEFT JOIN EMPLOYEE_MASTER E2
ON E1.MANAGERNO=E2.EMPLOYEENO
LEFT JOIN EMPLOYEE_MASTER E3 
ON E2.ManagerNo=E3.EmployeeNo
-- 20. Display managers and count of employees under them in descending order.
SELECT E2.NAME, COUNT(E1.EMPLOYEENO) 
FROM EMPLOYEE_MASTER E1
JOIN EMPLOYEE_MASTER E2 
ON E1.ManagerNo=E2.EmployeeNo
GROUP BY E2.NAME
ORDER BY COUNT(E1.EmployeeNo) DESC

SELECT * FROM EMPLOYEE_MASTER
